import 'dart:async';
import 'package:flutter/material.dart';
import 'dart:html' as html;
import 'dart:ui_web' as ui_web;

/// Web-specific iframe widget for Mautic with Edge Function auto-login
///
/// This widget loads Mautic via an iframe using the auto-login URL
/// generated by the Supabase Edge Function. The URL contains a one-time
/// token that automatically authenticates the user.
class MauticIframe extends StatefulWidget {
  final String loginUrl;
  final VoidCallback? onRefresh;
  final Function(String path)? onNavigate;

  const MauticIframe({
    super.key,
    required this.loginUrl,
    this.onRefresh,
    this.onNavigate,
  });

  @override
  State<MauticIframe> createState() => _MauticIframeState();
}

class _MauticIframeState extends State<MauticIframe> {
  static const String _mauticBaseUrl = 'https://email.moyd.app';

  String? _iframeId;
  html.IFrameElement? _iframe;
  bool _isLoading = true;
  bool _isRegistered = false;
  String _statusMessage = 'Loading Mautic...';
  String? _errorMessage;
  int _retryCount = 0;
  static const int _maxRetries = 3;

  @override
  void initState() {
    super.initState();
    _registerIframe();
  }

  @override
  void didUpdateWidget(MauticIframe oldWidget) {
    super.didUpdateWidget(oldWidget);
    // If login URL changed, reload iframe
    if (oldWidget.loginUrl != widget.loginUrl) {
      _reloadIframe();
    }
  }

  void _reloadIframe() {
    if (_iframe != null) {
      _iframe!.src = widget.loginUrl;
      setState(() {
        _isLoading = true;
        _statusMessage = 'Loading Mautic...';
        _errorMessage = null;
      });
    }
  }

  /// Register the iframe with the platform view registry
  void _registerIframe() {
    try {
      debugPrint('Mautic: Loading iframe with URL: ${widget.loginUrl}');

      // Create unique iframe ID
      final iframeId = 'mautic-iframe-${DateTime.now().millisecondsSinceEpoch}';

      _iframe = html.IFrameElement()
        ..src = widget.loginUrl
        ..style.border = 'none'
        ..style.width = '100%'
        ..style.height = '100%'
        ..allow = 'clipboard-read; clipboard-write'
        ..setAttribute('allowfullscreen', 'true')
        ..setAttribute('loading', 'eager');

      // Handle iframe load event
      _iframe!.onLoad.listen((_) {
        debugPrint('Mautic: Iframe loaded');
        _handleIframeLoaded();
      });

      // Handle iframe errors
      _iframe!.onError.listen((event) {
        debugPrint('Mautic: Iframe error: $event');
        _handleIframeError();
      });

      // Register the view factory
      ui_web.platformViewRegistry.registerViewFactory(
        iframeId,
        (int viewId) => _iframe!,
      );

      debugPrint('Mautic: Iframe registered, waiting for load...');

      if (mounted) {
        setState(() {
          _iframeId = iframeId;
          _isRegistered = true;
        });
      }
    } catch (e) {
      debugPrint('Mautic: Error registering iframe: $e');
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = 'Failed to initialize: $e';
        });
      }
    }
  }

  /// Handle successful iframe load
  void _handleIframeLoaded() {
    if (!mounted) return;

    debugPrint('Mautic: Iframe loaded successfully');

    // Hide loading after a short delay to ensure content is rendered
    Future.delayed(const Duration(milliseconds: 500), () {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = null;
        });
      }
    });
  }

  /// Handle iframe load error
  void _handleIframeError() {
    if (!mounted) return;

    if (_retryCount < _maxRetries) {
      _retryCount++;
      debugPrint('Mautic: Retrying... ($_retryCount/$_maxRetries)');

      setState(() {
        _statusMessage = 'Retrying... ($_retryCount/$_maxRetries)';
      });

      Future.delayed(const Duration(seconds: 2), () {
        if (mounted) {
          widget.onRefresh?.call();
        }
      });
    } else {
      setState(() {
        _isLoading = false;
        _errorMessage = 'Failed to load Mautic. Please try again or open in new tab.';
      });
    }
  }

  /// Open Mautic in a new tab
  void _openInNewTab() {
    html.window.open(widget.loginUrl, '_blank');
  }

  @override
  Widget build(BuildContext context) {
    // Show error if registration failed
    if (_errorMessage != null && !_isLoading && !_isRegistered) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.error_outline,
              size: 64,
              color: Colors.red.shade300,
            ),
            const SizedBox(height: 16),
            Text(
              _errorMessage!,
              style: const TextStyle(fontSize: 16),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 16),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton.icon(
                  onPressed: widget.onRefresh,
                  icon: const Icon(Icons.refresh),
                  label: const Text('Retry'),
                ),
                const SizedBox(width: 12),
                OutlinedButton.icon(
                  onPressed: _openInNewTab,
                  icon: const Icon(Icons.open_in_new),
                  label: const Text('Open in new tab'),
                ),
              ],
            ),
          ],
        ),
      );
    }

    // Wait for registration to complete before showing HtmlElementView
    if (!_isRegistered || _iframeId == null) {
      return Container(
        color: Colors.white,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const CircularProgressIndicator(),
              const SizedBox(height: 24),
              Text(
                _statusMessage,
                style: Theme.of(context).textTheme.titleMedium,
              ),
              const SizedBox(height: 8),
              Text(
                'Connecting to email campaign manager...',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: Colors.grey[600],
                ),
              ),
            ],
          ),
        ),
      );
    }

    // Show iframe with loading overlay and error banner
    return Stack(
      children: [
        // Iframe
        HtmlElementView(viewType: _iframeId!),

        // Loading overlay
        if (_isLoading)
          Container(
            color: Colors.white.withOpacity(0.9),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const CircularProgressIndicator(),
                  const SizedBox(height: 16),
                  Text(
                    _statusMessage,
                    style: const TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ),
          ),

        // Error banner (shown when load fails but iframe rendered)
        if (_errorMessage != null && !_isLoading)
          Positioned(
            top: 0,
            left: 0,
            right: 0,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              color: Colors.orange.shade100,
              child: Row(
                children: [
                  Icon(Icons.warning_amber, color: Colors.orange.shade800),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      _errorMessage!,
                      style: TextStyle(color: Colors.orange.shade900),
                    ),
                  ),
                  TextButton(
                    onPressed: _openInNewTab,
                    child: Text(
                      'Open in new tab',
                      style: TextStyle(color: Colors.orange.shade900),
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () {
                      setState(() {
                        _errorMessage = null;
                      });
                    },
                    iconSize: 20,
                    color: Colors.orange.shade800,
                  ),
                ],
              ),
            ),
          ),
      ],
    );
  }
}
