name: bitsdojo_window
version: 0.1.0
publish_to: 'none'
description: Web stub for bitsdojo_window to allow Flutter web builds.
environment:
  sdk: '>=3.1.3 <4.0.0'

flutter:
  plugin:
    platforms:
      web:
        pluginClass: StubPlugin
        fileName: stub.dart
