name: google_ml_kit
version: 1.0.0
publish_to: 'none'
description: Web stub for google_ml_kit.
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  google_mlkit_smart_reply:
    path: ../google_mlkit_smart_reply_stub
