# Netlify Configuration for BlueBubbles Flutter Web App

[build]
  # Build command
  command = "flutter build web --web-renderer auto --release"

  # Output directory
  publish = "build/web"

  # Environment variables for build
  [build.environment]
    FLUTTER_VERSION = "3.24.0"
    FLUTTER_CHANNEL = "stable"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Context-specific builds
[context.production]
  command = "flutter build web --web-renderer auto --release"

[context.deploy-preview]
  command = "flutter build web --web-renderer auto --release"

[context.branch-deploy]
  command = "flutter build web --web-renderer auto --release"

# Functions (if needed in the future)
[functions]
  directory = "functions"
