#!/bin/bash
# Netlify build script for Flutter web

set -eo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

FLUTTER_ROOT="${FLUTTER_ROOT:-/opt/buildhome/.flutter}"
FLUTTER_VERSION="${FLUTTER_VERSION:-3.41.8}"

# Download with retry logic
function download_with_retry() {
  local url="$1"
  local output="$2"
  local max_retries=4
  local retry_delay=2

  for ((i=1; i<=max_retries; i++)); do
    echo "Download attempt $i of $max_retries..."
    if curl -fSL --connect-timeout 30 --max-time 300 -o "$output" "$url"; then
      echo "Download successful!"
      return 0
    fi
    if [ $i -lt $max_retries ]; then
      echo "Download failed, retrying in ${retry_delay}s..."
      sleep $retry_delay
      retry_delay=$((retry_delay * 2))
    fi
  done
  echo "Download failed after $max_retries attempts"
  return 1
}

function ensure_flutter() {
  # Check if Flutter is already installed and correct version
  if [ -f "$FLUTTER_ROOT/bin/flutter" ]; then
    local installed_version
    installed_version=$("$FLUTTER_ROOT/bin/flutter" --version 2>/dev/null | head -1 | grep -oP '\d+\.\d+\.\d+' || echo "")
    if [ "$installed_version" = "$FLUTTER_VERSION" ]; then
      echo "Flutter SDK $FLUTTER_VERSION already installed."
      return 0
    fi
    echo "Flutter version mismatch (installed: $installed_version, required: $FLUTTER_VERSION). Reinstalling..."
  fi

  echo "Installing Flutter SDK ($FLUTTER_VERSION) from Google Storage..."
  rm -rf "$FLUTTER_ROOT"
  mkdir -p "$FLUTTER_ROOT"

  # Download Flutter from Google's storage (avoids GitHub DNS issues)
  local flutter_archive="flutter_linux_${FLUTTER_VERSION}-stable.tar.xz"
  local flutter_url="https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/$flutter_archive"
  local tmp_archive="/tmp/$flutter_archive"

  echo "Downloading from: $flutter_url"
  if ! download_with_retry "$flutter_url" "$tmp_archive"; then
    echo "Error: Failed to download Flutter SDK"
    exit 1
  fi

  echo "Extracting Flutter SDK..."
  tar -xf "$tmp_archive" -C "$FLUTTER_ROOT" --strip-components=1

  rm -f "$tmp_archive"
  echo "Flutter SDK installed successfully!"
}

ensure_flutter

export PATH="$FLUTTER_ROOT/bin:$FLUTTER_ROOT/bin/cache/dart-sdk/bin:$PATH"
command -v flutter >/dev/null || { echo "Flutter SDK missing"; exit 1; }

function write_flutter_env() {
  local env_file=".env"
  declare -A merged_env=()

  if [[ -f "$env_file" ]]; then
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
      [[ -z "$key" ]] && continue
      [[ "$key" =~ ^# ]] && continue
      merged_env["$key"]="$value"
    done < "$env_file"
  fi

  local env_vars=(
    NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_HOST
    NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_URL
    NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_PASSWORD
    NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_AUTH_KEY
    BLUEBUBBLES_PRIVATE_API_HOST
    BLUEBUBBLES_PRIVATE_API_URL
    BLUEBUBBLES_PRIVATE_API_PASSWORD
    BLUEBUBBLES_PRIVATE_API_AUTH_KEY
    NEXT_PUBLIC_BLUEBUBBLES_HOST
    NEXT_PUBLIC_BLUEBUBBLES_URL
    NEXT_PUBLIC_BLUEBUBBLES_PASSWORD
    NEXT_PUBLIC_BLUEBUBBLES_AUTH_KEY
    BLUEBUBBLES_HOST
    BLUEBUBBLES_URL
    BLUEBUBBLES_PASSWORD
    BLUEBUBBLES_AUTH_KEY
    SUPABASE_URL
    SUPABASE_ANON_KEY
    NEXT_PUBLIC_SUPABASE_URL
    NEXT_PUBLIC_SUPABASE_ANON_KEY
    MAPKIT_TOKEN_MOYD
    MAPKIT_TOKEN_NETLIFY
  )

  local has_value=false
  for var in "${env_vars[@]}"; do
    if [[ -n "${!var:-}" ]]; then
      merged_env["$var"]="${!var}"
      has_value=true
    fi
  done

  if [[ "$has_value" == true ]]; then
    {
      echo "# Generated by Netlify build from environment variables"
      for key in "${!merged_env[@]}"; do
        printf '%s=%s\n' "$key" "${merged_env[$key]}"
      done | sort
    } > "$env_file"
    echo "Updated runtime .env configuration for Flutter web build."
  fi
}

flutter --version
flutter config --enable-web
flutter precache --web

echo "Installing dependencies..."
write_flutter_env
flutter pub get

# Patch linagora git deps for Flutter 3.24 compatibility (they use 3.27+ APIs).
# Required for the tmail-flutter source fork to build. See tool/patch_pub_cache.sh.
echo "Patching linagora git deps in pub-cache for Flutter 3.24 compatibility..."
bash tool/patch_pub_cache.sh

if grep -q "build_runner" pubspec.yaml; then
  echo "Running code generation..."
  flutter pub run build_runner build --delete-conflicting-outputs
fi

echo "Building web app..."

# Sentry release must match between the SDK (dart-define) and the source map
# uploader (sentry_dart_plugin reads SENTRY_RELEASE from the environment).
PUBSPEC_VERSION="$(grep -m1 '^version:' pubspec.yaml | awk '{print $2}')"
export SENTRY_RELEASE="${SENTRY_RELEASE:-bluebubbles@${PUBSPEC_VERSION}}"

declare -a dart_define_args=()
for var in \
  NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_HOST \
  NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_URL \
  NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_PASSWORD \
  NEXT_PUBLIC_BLUEBUBBLES_PRIVATE_API_AUTH_KEY \
  BLUEBUBBLES_PRIVATE_API_HOST \
  BLUEBUBBLES_PRIVATE_API_URL \
  BLUEBUBBLES_PRIVATE_API_PASSWORD \
  BLUEBUBBLES_PRIVATE_API_AUTH_KEY \
  NEXT_PUBLIC_BLUEBUBBLES_HOST \
  NEXT_PUBLIC_BLUEBUBBLES_URL \
  NEXT_PUBLIC_BLUEBUBBLES_PASSWORD \
  NEXT_PUBLIC_BLUEBUBBLES_AUTH_KEY \
  BLUEBUBBLES_HOST \
  BLUEBUBBLES_URL \
  BLUEBUBBLES_PASSWORD \
  BLUEBUBBLES_AUTH_KEY \
  SUPABASE_URL \
  SUPABASE_ANON_KEY \
  NEXT_PUBLIC_SUPABASE_URL \
  NEXT_PUBLIC_SUPABASE_ANON_KEY \
  MAPKIT_TOKEN_MOYD \
  MAPKIT_TOKEN_NETLIFY \
  SENTRY_DSN \
  SENTRY_RELEASE; do
  if [[ -n "${!var:-}" ]]; then
    dart_define_args+=("--dart-define=${var}=${!var}")
  fi
done

# --wasm emits TWO builds and a buildConfig that lets the loader choose:
#   dart2wasm + skwasm  (main.dart.wasm)  for browsers with WasmGC
#   dart2js  + canvaskit (main.dart.js)   for everything else
# So this is additive. Any browser that cannot run wasm gets byte-for-byte
# what it gets today. web/index.html opts WebKit in via wasmAllowList, because
# Flutter 3.41.8 still hard-codes webkit:false despite WasmGC shipping in
# Safari 18.2 / iOS 18.2.
#
# --source-maps is dropped here: it is a dart2js flag, and passing it
# alongside --wasm is not a supported combination. Sentry still symbolicates
# the JS build from the debug info the build emits; if JS source maps turn out
# to be needed, the fix is a second `flutter build web` pass, not re-adding the
# flag to this one.
flutter build web --wasm --release --no-tree-shake-icons "${dart_define_args[@]}"

# Fail loudly rather than deploying half a build. If the wasm artifact is
# missing, the loader would silently serve the JS build to every device and the
# whole point of this change would be lost without anyone noticing.
if [[ ! -f build/web/main.dart.wasm ]]; then
  echo "ERROR: --wasm build did not emit build/web/main.dart.wasm" >&2
  exit 1
fi
if [[ ! -f build/web/main.dart.js ]]; then
  echo "ERROR: --wasm build did not emit the dart2js fallback build/web/main.dart.js" >&2
  exit 1
fi
echo "Emitted both builds:"
ls -la build/web/main.dart.wasm build/web/main.dart.js

if [[ -n "${SENTRY_AUTH_TOKEN:-}" ]]; then
  echo "Uploading symbols to Sentry (release: $SENTRY_RELEASE)..."
  # Non-fatal on purpose. The script runs under `set -e`, and dropping
  # --source-maps for the --wasm build means sentry_dart_plugin may find
  # nothing to upload and exit non-zero. A missing symbol upload degrades
  # stack traces in Sentry; it is not a reason to fail a deploy that is
  # otherwise good. The warning below is the signal to go look.
  if ! dart run sentry_dart_plugin; then
    echo "WARNING: Sentry symbol upload failed. The build is still valid, but" >&2
    echo "         traces for release $SENTRY_RELEASE will not be symbolicated." >&2
  fi
else
  echo "SENTRY_AUTH_TOKEN not set; skipping Sentry symbol upload."
fi

echo "Build complete! Output in build/web/"
