[build]
  command = "bash netlify-build.sh"
  publish = "build/web"

[build.environment]
  # Flutter requires Git
  GIT_LFS_ENABLED = "true"
  # Pin the Flutter version so Netlify uses the same toolchain as local builds
  FLUTTER_VERSION = "3.24.4"

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
