// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/caching/entries/sentry_configuration_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/caching/entries/sentry_user_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/home/data/model/session_hive_obj.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/account_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/authentication_info_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/encryption_key_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/oidc_configuration_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/recent_login_url_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/recent_login_username_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/login/data/model/token_oidc_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/mailbox/data/model/mailbox_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/mailbox/data/model/mailbox_rights_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/mailbox/data/model/state_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/mailbox/data/model/state_type.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/mailbox_dashboard/data/model/recent_search_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/offline_mode/model/attachment_hive_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/offline_mode/model/detailed_email_hive_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/offline_mode/model/email_header_hive_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/offline_mode/model/sending_email_hive_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/push_notification/data/model/firebase_registration_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/thread/data/model/email_address_hive_cache.dart';
import 'package:bluebubbles/features/mail/_tmail/tmail_ui_user/features/thread/data/model/email_cache.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountCacheAdapter());
    registerAdapter(AttachmentHiveCacheAdapter());
    registerAdapter(AuthenticationInfoCacheAdapter());
    registerAdapter(DetailedEmailHiveCacheAdapter());
    registerAdapter(EmailAddressHiveCacheAdapter());
    registerAdapter(EmailCacheAdapter());
    registerAdapter(EmailHeaderHiveCacheAdapter());
    registerAdapter(EncryptionKeyCacheAdapter());
    registerAdapter(FirebaseRegistrationCacheAdapter());
    registerAdapter(MailboxCacheAdapter());
    registerAdapter(MailboxRightsCacheAdapter());
    registerAdapter(OidcConfigurationCacheAdapter());
    registerAdapter(RecentLoginUrlCacheAdapter());
    registerAdapter(RecentLoginUsernameCacheAdapter());
    registerAdapter(RecentSearchCacheAdapter());
    registerAdapter(SendingEmailHiveCacheAdapter());
    registerAdapter(SentryConfigurationCacheAdapter());
    registerAdapter(SentryUserCacheAdapter());
    registerAdapter(SessionHiveObjAdapter());
    registerAdapter(StateCacheAdapter());
    registerAdapter(StateTypeAdapter());
    registerAdapter(TokenOidcCacheAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountCacheAdapter());
    registerAdapter(AttachmentHiveCacheAdapter());
    registerAdapter(AuthenticationInfoCacheAdapter());
    registerAdapter(DetailedEmailHiveCacheAdapter());
    registerAdapter(EmailAddressHiveCacheAdapter());
    registerAdapter(EmailCacheAdapter());
    registerAdapter(EmailHeaderHiveCacheAdapter());
    registerAdapter(EncryptionKeyCacheAdapter());
    registerAdapter(FirebaseRegistrationCacheAdapter());
    registerAdapter(MailboxCacheAdapter());
    registerAdapter(MailboxRightsCacheAdapter());
    registerAdapter(OidcConfigurationCacheAdapter());
    registerAdapter(RecentLoginUrlCacheAdapter());
    registerAdapter(RecentLoginUsernameCacheAdapter());
    registerAdapter(RecentSearchCacheAdapter());
    registerAdapter(SendingEmailHiveCacheAdapter());
    registerAdapter(SentryConfigurationCacheAdapter());
    registerAdapter(SentryUserCacheAdapter());
    registerAdapter(SessionHiveObjAdapter());
    registerAdapter(StateCacheAdapter());
    registerAdapter(StateTypeAdapter());
    registerAdapter(TokenOidcCacheAdapter());
  }
}
