-- Make the watchdog's alert prove it was delivered.
--
-- FOUND BY DRILLING IT. The first fire drill raised the alarm correctly, but the
-- pg_net POST to Telegram came back
--   "Timeout of 5000 ms reached ... DNS time: 5000.080000 ms"
-- because net.http_post defaults to a 5 second timeout and DNS from the database
-- is not reliably that fast. An alert that quietly times out is precisely the
-- silent failure this whole watchdog exists to prevent, so:
--
--   1. give the alert a 20 second timeout, and
--   2. record the pg_net request id, so the NEXT run can look at whether the
--      last alert actually landed. An alarm that failed to deliver no longer
--      suppresses the next one.

alter table public.slack_token_rotation_log
  add column if not exists alert_request_id bigint;

comment on column public.slack_token_rotation_log.alert_request_id is
  'pg_net request id of the Telegram alert for this row. Join to net._http_response to see whether the alert actually got out.';

create or replace function public.fn_slack_token_rotation_watchdog()
returns text
language plpgsql
security definer
set search_path = public, vault, net
as $$
declare
  v_status   text;
  v_health   record;
  v_recent   boolean;
  v_token    text;
  v_chat     text;
  v_msg      text;
  v_log_id   bigint;
  v_req_id   bigint;
begin
  select * into v_health from public.v_slack_token_rotation_health;
  v_status := v_health.status;

  if v_status = 'OK' then
    return 'OK';
  end if;

  -- Stay quiet only if a recent alarm actually REACHED Telegram, or is still in
  -- flight. A timed-out or failed alert must not buy silence.
  select exists (
    select 1
      from public.slack_token_rotation_log l
      left join net._http_response r on r.id = l.alert_request_id
     where l.status = 'watchdog_alarm'
       and l.started_at > now() - interval '1 hour'
       and (
         r.status_code = 200
         or (r.id is null and l.started_at > now() - interval '2 minutes')
       )
  ) into v_recent;

  if v_recent then
    return v_status || ' (already alerted, and that alert was delivered)';
  end if;

  v_msg := 'MOYD Slack app-config token rotation is ' || v_status || E'.\n'
        || 'last success: ' || coalesce(v_health.last_success_at::text, 'never')
        || ' (' || coalesce(v_health.hours_since_success::text, 'n/a') || 'h ago)' || E'\n'
        || 'token expires: ' || coalesce(v_health.token_expires_at::text, 'unknown') || E'\n'
        || 'stuck attempts: ' || v_health.stuck_attempts
        || ', persist failures (7d): ' || v_health.persist_failures_7d || E'\n'
        || 'If this says LOST or STUCK, programmatic Slack app-config access may be gone '
        || 'and a new token must be generated by hand at api.slack.com/authentication/config-tokens, '
        || 'then re-seeded with moyd-ops/slack/tools/seed.mjs.';

  select decrypted_secret into v_token from vault.decrypted_secrets where name = 'telegram_alert_bot_token';
  select decrypted_secret into v_chat  from vault.decrypted_secrets where name = 'telegram_alert_chat_id';

  if v_token is not null and v_chat is not null then
    select net.http_post(
      url     := 'https://api.telegram.org/bot' || v_token || '/sendMessage',
      headers := '{"Content-Type": "application/json"}'::jsonb,
      body    := jsonb_build_object('chat_id', v_chat, 'text', v_msg),
      timeout_milliseconds := 20000
    ) into v_req_id;
  end if;

  insert into public.slack_token_rotation_log (status, trigger_source, note, finished_at, alert_request_id)
  values ('watchdog_alarm', 'watchdog', left(v_msg, 2000), now(), v_req_id)
  returning id into v_log_id;

  return v_status || ' (alarm raised, log id ' || v_log_id || ', alert request ' || coalesce(v_req_id::text, 'none') || ')';
end;
$$;

revoke all on function public.fn_slack_token_rotation_watchdog() from public, anon, authenticated;
