-- NOTE (2026-07-23): the anon write grants and FOR ALL policy originally in this
-- file were SUPERSEDED the same day by migrations_manual/20260723_tighten_new_table_grants.sql
-- (anon is SELECT-only; writes via service_role/postgres). Kept here unmodified below
-- as the historical record of what was first applied.
-- 20260723_01_fec_expenditures.sql
-- FEC operating-expenditures (oppexp) mirror table.
-- Modeled on the FEC bulk oppexp layout + our public.fec_contributions conventions.
-- RLS + grants mirror public.fec_contributions exactly.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fec_expenditures (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cmte_id                text,
  amndt_ind              text,
  rpt_yr                 int,
  rpt_tp                 text,
  image_num              text,
  line_num               text,
  form_tp_cd             text,
  sched_tp_cd            text,
  payee_name             text,
  city                   text,
  state                  text,
  zip                    text,
  transaction_dt         date,
  transaction_amt        numeric,
  transaction_pgi        text,
  purpose                text,
  category               text,
  category_desc          text,
  entity_tp              text,
  sub_id                 text UNIQUE,
  file_num               bigint,
  tran_id                text,
  back_ref_tran_id       text,
  memo_cd                text,
  memo_text              text,
  cycle                  int,
  parsed_payee_company   text,
  parsed_payee_last      text,
  parsed_payee_first     text,
  created_at             timestamptz DEFAULT now(),
  updated_at             timestamptz DEFAULT now()
);

-- Indexes (mirror fec_contributions conventions).
CREATE INDEX IF NOT EXISTS idx_fec_expenditures_cmte_cycle
  ON public.fec_expenditures USING btree (cmte_id, cycle);
CREATE INDEX IF NOT EXISTS idx_fec_expenditures_cmte_date
  ON public.fec_expenditures USING btree (cmte_id, transaction_dt);
-- pg_trgm is installed, so add a trigram index for payee fuzzy search.
CREATE INDEX IF NOT EXISTS idx_fec_expenditures_payee_trgm
  ON public.fec_expenditures USING gin (payee_name gin_trgm_ops);

-- RLS: mirror fec_contributions (permissive read-all policy, all commands).
ALTER TABLE public.fec_expenditures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS fec_expenditures_read ON public.fec_expenditures;
CREATE POLICY fec_expenditures_read
  ON public.fec_expenditures
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Grants: mirror fec_contributions exactly.
--   authenticated / service_role / postgres: ALL (DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE)
--   anon: INSERT, REFERENCES, SELECT, TRIGGER, UPDATE (no DELETE / TRUNCATE)
GRANT ALL ON public.fec_expenditures TO authenticated;
GRANT ALL ON public.fec_expenditures TO service_role;
GRANT ALL ON public.fec_expenditures TO postgres;
GRANT INSERT, REFERENCES, SELECT, TRIGGER, UPDATE ON public.fec_expenditures TO anon;

COMMIT;
